### ISSUE TITLE
Unable to run sails lift (with migrate: 'drop') when dependency subclassed models are created.

### ISSUE THREAD

**Issue by rh0dium** [appscot/sails-orientdb#120]
Hi there,

If you subclass models you cannot run sails lift.  You will get the following error.

    error: A hook (`orm`) failed to load!
    error: Error (E_UNKNOWN) :: Encountered an unexpected error
    OrientDB.RequestError: Class 'pmobject' cannot be dropped because it has sub classes. Remove the dependencies before trying to drop it again
        at Operation.parseError (/Users/sklass/Development/gdp_server/node_modules/sails-orientdb/node_modules/oriento/lib/transport/binary/protocol28/operation.js:832:13)
        at Operation.consume (/Users/sklass/Development/gdp_server/node_modules/sails-orientdb/node_modules/oriento/lib/transport/binary/protocol28/operation.js:422:35)

**Comment by dmarcelino** [comment]
Hi @rh0dium, this doesn't look like a `sails-orientdb` issue. Have you tried other adapters such as sails-memory or sails-disk?

**Comment by dmarcelino** [comment]
Closing this as unresponsive, please re-open after providing more information.
