### ISSUE TITLE
Database being dropped

### ISSUE THREAD

**Issue by tommykennedy** [appscot/sails-orientdb#126]
I am getting a very unusual situation where Sails seems to drop my database for no reason. I start the database in safe mode after dropping it to clear out test data.

The trace output is below.

Im not sure if there is any indication of why the database is dropping and these errors occur?

error: Failed to reinitialize ORM.
error: Error (E_UNKNOWN) :: Encountered an unexpected error
: Trying to define a collection (Answer) which already exists.
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:45:40
    at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at callback.success (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at /Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:118:9
    at tryCatcher (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/bluebird/js/main/promise.js:489:31)
    at Promise._settlePromiseAt (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/bluebird/js/main/promise.js:565:18)
    at Promise._settlePromiseAtPostResolution (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/bluebird/js/main/promise.js:244:10)
    at Async._drainQueue (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

Details:  Error: Trying to define a collection (Answer) which already exists.

Unhandled rejection Error: [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Trying to define a collection (Answer) which already exists.

    at /usr/local/lib/node_modules/sails/lib/hooks/orm/index.js:221:19
    at taskCallback (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:471:21)
    at /usr/local/lib/node_modules/sails/lib/hooks/orm/build-orm.js:57:23
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:213:22
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:151:21
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/index.js:69:22
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/drop.js:36:10
    at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:331:16)
    at callback.error (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:42:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:46:28)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:45:37
    at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at callback.success (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at /Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:118:9
From previous event:
    at Connection.describe (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:94:6)
    at Object.module.exports.adapter.describe (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/adapter.js:218:31)
    at module.exports.describe (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:80:13)
    at module.exports.define (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:43:10)
    at afterDrop (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/drop.js:35:10)
    at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at callback.success (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at Db.<anonymous> (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/collection/document.js:270:7)
From previous event:
    at Document.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/collection/document.js:268:6)
    at Vertex.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/collection/vertex.js:74:39)
    at Connection.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:365:14)
    at Object.module.exports.adapter.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/adapter.js:256:38)
    at module.exports.drop (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:111:13)
    at drop [as migrateDrop] (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/drop.js:32:8)
    at Query.sync (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/index.js:68:37)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:288:16
    at iterate (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:149:13)
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:160:25
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/index.js:70:7
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/drop.js:36:10
    at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at callback.success (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at /Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:189:11
    at Connection._ensureIndexes (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:472:49)
    at Db.<anonymous> (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:179:12)
From previous event:
    at Connection.createCollection (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:165:6)
    at Object.module.exports.adapter.define (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/adapter.js:238:31)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:60:15
    at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at callback.success (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at Connection.describe (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:89:42)
    at Object.module.exports.adapter.describe (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/adapter.js:218:31)
    at module.exports.describe (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:80:13)
    at module.exports.define (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:43:10)
    at afterDrop (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/drop.js:35:10)
    at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at callback.success (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at Db.<anonymous> (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/collection/document.js:270:7)
From previous event:
    at Document.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/collection/document.js:268:6)
    at null.<anonymous> (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/collection/vertex.js:80:34)
From previous event:
    at Vertex.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/collection/vertex.js:78:6)
    at Connection.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:365:14)
    at Object.module.exports.adapter.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/adapter.js:256:38)
    at module.exports.drop (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:111:13)
    at drop [as migrateDrop] (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/drop.js:32:8)
    at Query.sync (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/index.js:68:37)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:288:16
    at iterate (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:165:9)
    at bootstrap (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:286:9)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:212:10
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:454:17
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:444:17
    at Array.forEach (native)
    at _each (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:46:24)
    at Immediate.taskComplete (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:443:13)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
error: Failed to reinitialize ORM.
error: Error (E_UNKNOWN) :: Encountered an unexpected error
OrientDB.RequestError: Error on parsing command at position #0: Class 'ANSWER' was not found
    at Operation.parseError (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/oriento/lib/transport/binary/protocol28/operation.js:879:13)
    at Operation.consume (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/oriento/lib/transport/binary/protocol28/operation.js:469:35)
    at Connection.process (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/oriento/lib/transport/binary/connection.js:380:17)
    at Connection.handleSocketData (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/oriento/lib/transport/binary/connection.js:281:17)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
From previous event:
    at Connection._sendOp (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/oriento/lib/transport/binary/connection.js:81:10)
    at Connection.send (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/oriento/lib/transport/binary/connection.js:65:17)
    at BinaryTransport.send (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/oriento/lib/transport/binary/index.js:191:43)
    at Server.send (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/oriento/lib/server/index.js:112:25)
    at Db.<anonymous> (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/oriento/lib/db/index.js:152:24)
From previous event:
    at Db.send (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/oriento/lib/db/index.js:144:4)
    at Db.exec (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/oriento/lib/db/index.js:247:22)
    at Db.query (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/oriento/lib/db/index.js:279:15)
    at module.exports.Statement.extend.exec (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/oriento/lib/db/query.js:108:20)
    at module.exports.Statement.extend.one (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/node_modules/oriento/lib/db/query.js:57:17)
    at Vertex.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/collection/vertex.js:77:64)
    at Connection.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:365:14)
    at Object.module.exports.adapter.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/adapter.js:256:38)
    at module.exports.drop (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:111:13)
    at drop [as migrateDrop] (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/drop.js:32:8)
    at Query.sync (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/index.js:68:37)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:288:16
    at iterate (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:149:13)
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:160:25
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/index.js:70:7
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/drop.js:36:10
    at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at callback.success (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at /Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:189:11
    at Connection._ensureIndexes (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:472:49)
    at Db.<anonymous> (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:179:12)
From previous event:
    at Connection.createCollection (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:165:6)
    at Object.module.exports.adapter.define (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/adapter.js:238:31)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:60:15
    at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at callback.success (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at Connection.describe (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:89:42)
    at Object.module.exports.adapter.describe (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/adapter.js:218:31)
    at module.exports.describe (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:80:13)
    at module.exports.define (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:43:10)
    at afterDrop (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/drop.js:35:10)
    at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at callback.success (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at Db.<anonymous> (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/collection/document.js:270:7)
From previous event:
    at Document.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/collection/document.js:268:6)
    at null.<anonymous> (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/collection/vertex.js:80:34)
From previous event:
    at Vertex.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/collection/vertex.js:78:6)
    at Connection.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:365:14)
    at Object.module.exports.adapter.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/adapter.js:256:38)
    at module.exports.drop (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:111:13)
    at drop [as migrateDrop] (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/drop.js:32:8)
    at Query.sync (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/index.js:68:37)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:288:16
    at iterate (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:165:9)
    at bootstrap (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:286:9)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:212:10
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:454:17
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:444:17
    at Array.forEach (native)
    at _each (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:46:24)
    at Immediate.taskComplete (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:443:13)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

Details:  OrientDB.RequestError: Error on parsing command at position #0: Class 'ANSWER' was not found

Unhandled rejection Error: [Error (E_UNKNOWN) Encountered an unexpected error] Details:  OrientDB.RequestError: Error on parsing command at position #0: Class 'ANSWER' was not found

    at /usr/local/lib/node_modules/sails/lib/hooks/orm/index.js:221:19
    at taskCallback (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:471:21)
    at /usr/local/lib/node_modules/sails/lib/hooks/orm/build-orm.js:57:23
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:213:22
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:151:21
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/index.js:69:22
    at afterDrop (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/drop.js:33:21)
    at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:331:16)
    at callback.error (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:42:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:46:28)
From previous event:
    at Vertex.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/collection/vertex.js:82:6)
    at Connection.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:365:14)
    at Object.module.exports.adapter.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/adapter.js:256:38)
    at module.exports.drop (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:111:13)
    at drop [as migrateDrop] (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/drop.js:32:8)
    at Query.sync (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/index.js:68:37)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:288:16
    at iterate (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:149:13)
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:160:25
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/index.js:70:7
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/drop.js:36:10
    at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at callback.success (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at /Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:189:11
    at Connection._ensureIndexes (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:472:49)
    at Db.<anonymous> (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:179:12)
From previous event:
    at Connection.createCollection (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:165:6)
    at Object.module.exports.adapter.define (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/adapter.js:238:31)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:60:15
    at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at callback.success (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at Connection.describe (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:89:42)
    at Object.module.exports.adapter.describe (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/adapter.js:218:31)
    at module.exports.describe (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:80:13)
    at module.exports.define (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:43:10)
    at afterDrop (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/drop.js:35:10)
    at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at callback.success (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at Db.<anonymous> (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/collection/document.js:270:7)
From previous event:
    at Document.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/collection/document.js:268:6)
    at null.<anonymous> (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/collection/vertex.js:80:34)
From previous event:
    at Vertex.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/collection/vertex.js:78:6)
    at Connection.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/connection.js:365:14)
    at Object.module.exports.adapter.drop (/Users/thomaskenedy/sandbox/LegoEight/node_modules/sails-orientdb/lib/adapter.js:256:38)
    at module.exports.drop (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:111:13)
    at drop [as migrateDrop] (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/drop.js:32:8)
    at Query.sync (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/index.js:68:37)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:288:16
    at iterate (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:165:9)
    at bootstrap (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:286:9)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:212:10
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:454:17
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:444:17
    at Array.forEach (native)
    at _each (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:46:24)
    at Immediate.taskComplete (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:443:13)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by dmarcelino** [comment]
I can't think of any scenario where sails-orientdb drops the database, only tables. Are you using `migrate: 'drop'`? That would drop every table at start up. Which version of OrientDB are you using?

**Comment by tommykennedy** [comment]
No migrate:drop. It seems to occur intermittently when I save changes to code when the sails server is lifted.

**Comment by dmarcelino** [comment]
Which version of OrientDB are you using?

**Comment by tommykennedy** [comment]
2.0.10. I will close this for now and will spend some more time trying to replicate and debug.
