### ISSUE TITLE
Many-to-Many sample code not working

### ISSUE THREAD

**Issue by chrisns** [appscot/sails-orientdb#98]
Hello,
Just getting to grips with orientdb (2.1 rc2) + sails.
I'm currently getting this error when running `node node_modules/sails-orientdb/example/associations/many-to-many.js`
```
Waterline initialized

Unhandled rejection Error (E_UNKNOWN) :: Encountered an unexpected error
OrientDB.RequestError: Error on parsing command at position #0: Encountered " <RECORD_ATTRIBUTE> "@rid "" at line 1, column 193.
Was expecting one of:
    <TO> ...
    <VALUES> ...
    <SET> ...
    <ADD> ...
    <PUT> ...
    <MERGE> ...
    <CONTENT> ...
    <REMOVE> ...
    <ORDER> ...
    <GROUP> ...
    <OFFSET> ...
    <RECORD> ...
    <LUCENE> ...
    <IN> ...
    <KEY> ...
    <IDENTIFIER> ...
    
    at Operation.parseError (/httpdocs/wc-node/node_modules/sails-orientdb/node_modules/oriento/lib/transport/binary/protocol28/operation.js:832:13)
    at Operation.consume (/httpdocs/wc-node/node_modules/sails-orientdb/node_modules/oriento/lib/transport/binary/protocol28/operation.js:422:35)
    at Connection.process (/httpdocs/wc-node/node_modules/sails-orientdb/node_modules/oriento/lib/transport/binary/connection.js:360:17)
    at Connection.handleSocketData (/httpdocs/wc-node/node_modules/sails-orientdb/node_modules/oriento/lib/transport/binary/connection.js:279:17)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)
```
node doesn't exit

and this error from the server
```
com.orientechnologies.orient.core.sql.parser.ParseException: Encountered " <RECORD_ATTRIBUTE> "@rid "" at line 1, column 193.
Was expecting one of:
    <TO> ...
    <VALUES> ...
    <SET> ...
    <ADD> ...
    <PUT> ...
    <MERGE> ...
    <CONTENT> ...
    <REMOVE> ...
    <ORDER> ...
    <GROUP> ...
    <OFFSET> ...
    <RECORD> ...
    <LUCENE> ...
    <IN> ...
    <KEY> ...
    <IDENTIFIER> ...
    
	at com.orientechnologies.orient.core.sql.parser.OrientSql.generateParseException(OrientSql.java:11861)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_consume_token(OrientSql.java:11734)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.Identifier(OrientSql.java:174)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.UpdateItem(OrientSql.java:2003)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.UpdateOperations(OrientSql.java:1869)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.UpdateStatement(OrientSql.java:1692)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.Statement(OrientSql.java:341)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.parse(OrientSql.java:87)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:234)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.parse(OCommandExecutorSQLUpdate.java:100)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.parse(OCommandExecutorSQLUpdate.java:66)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:74)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:40)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1181)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1172)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:372)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:221)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)
Sent run-time exception to the client /127.0.0.1:56633: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered " <RECORD_ATTRIBUTE> "@rid "" at line 1, column 193.
Was expecting one of:
    <TO> ...
    <VALUES> ...
    <SET> ...
    <ADD> ...
    <PUT> ...
    <MERGE> ...
    <CONTENT> ...
    <REMOVE> ...
    <ORDER> ...
    <GROUP> ...
    <OFFSET> ...
    <RECORD> ...
    <LUCENE> ...
    <IN> ...
    <KEY> ...
    <IDENTIFIER> ...
    
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered " <RECORD_ATTRIBUTE> "@rid "" at line 1, column 193.
Was expecting one of:
    <TO> ...
    <VALUES> ...
    <SET> ...
    <ADD> ...
    <PUT> ...
    <MERGE> ...
    <CONTENT> ...
    <REMOVE> ...
    <ORDER> ...
    <GROUP> ...
    <OFFSET> ...
    <RECORD> ...
    <LUCENE> ...
    <IN> ...
    <KEY> ...
    <IDENTIFIER> ...
    
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.throwParsingException(OCommandExecutorSQLAbstract.java:99)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:244)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.parse(OCommandExecutorSQLUpdate.java:100)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.parse(OCommandExecutorSQLUpdate.java:66)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:74)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:40)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1181)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1172)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:372)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:221)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)

```

The vertexes get made but not the edges

Any thoughts would be really helpful

**Comment by dmarcelino** [comment]
Hi @chrisns, OrientDB 2.1 is not supported yet, check #52. Have you tried the same with OrientDB 2.0?

**Comment by chrisns** [comment]
Hey, ah ok cool, yup works fine with 2.0.9
I had seen that but didn't grasp what the end effects of the issue were, thanks the fast response.
I'll stick to 2.0.9 for now then!
Cheers

**Comment by dmarcelino** [comment]
That's probably best, you're welcome.

**Comment by joelmcs6** [comment]
Hi could you please tell me if  you already support version 2.1 ? Thanks !

**Comment by dmarcelino** [comment]
Hi @joelmcs6, sails-orientdb does not support OrientDB v2.1, check #52.
